### PR TITLE
Updated to xNormal 3.19.3 and fixed some typos

### PR DESCRIPTION
**Pull request by moppius**
This PR is adds some functionality from the newer xNormal 3.19.3 version, and fixes some minor issues which had always existed.

# Additions
* Added `cage_file` parameter for low-poly control cage file paths
* Added `base_texture` parameter for high-poly base textures
* Support for new translucency baking parameters

# Fixes
* Normal swizzle parameters now have unique names (used to all be `normal_x`)
* Typo fix (`derivitive` should have been `derivative`) - this will break anything that people are dependent on for this parameter, but it's a fairly lesser-used parameter, I think
* Newline and spacing fixes

I regenerated the built version using the setup.py, but I wasn't sure what parameters were used to generate the archives and binaries in the _dist_ folder, so please either let me know what commands should be used, or otherwise they can be generated after this PR is merged.

### CODE REVIEW

**Comment by orangeduck** [comment]
Awesome, thanks so much!

**Comment by moppius** [comment]
No problem!

I guess the `dist` stuff still needs to be updated, as well as the things for PyPi distribution, but I don't know how to do that.

I didn't get around to adding a nicer method for setting the `PositionOffset` values, but if people really want to use that they can set it as a string for now. I might add support for that next week just for completeness.

**Comment by orangeduck** [comment]
Thanks I'll try to get around to updating the `dist` stuff and pushing the update to PyPI next week.

**Comment by orangeduck** [comment]
Okay I've updated the dist on PyPI etc.

**Pull request merged**
